### PR TITLE
Issue #61 allow application to use any major version of .net core 3.1

### PR DESCRIPTION
**Pull request by mosoftwareenterprises**
## Description of Change

Change Github actions files to allow building on any version of .net core 3.1.200 or higher

## Evidence Of Change

A picture of the Actions completed view:
image

## Linked Issue

Links to Issue #61

### CODE REVIEW

**Review by wordshaker — APPROVED** [review]

**Comment by wordshaker** [comment]
Excellent change! Thanks @mosoftwareenterprises

**Review by pjgpetecodes — CHANGES_REQUESTED** [review]
I've got a feeling that the global.json file may require the use of `latestFeature` rather than `latestMajor`, as this will currently try to use .NET 5 if it's installed on the host machine I think?

There's a really great post here about how all the different rollForward options work...

https://andrewlock.net/exploring-the-new-rollforward-and-allowprerelease-settings-in-global-json/

**Comment by mosoftwareenterprises** [comment]
I'll take a look tomorrow.

**Comment by mosoftwareenterprises** [comment]
> I've got a feeling that the global.json file may require the use of `latestFeature` rather than `latestMajor`, as this will currently try to use .NET 5 if it's installed on the host machine I think?
> 
> There's a really great post here about how all the different rollForward options work...
> 
> https://andrewlock.net/exploring-the-new-rollforward-and-allowprerelease-settings-in-global-json/

Based on that article, you are right, this will currently use any SDK later that 3.1.200. I'll change it. Thanks for the headsup

**Comment by mosoftwareenterprises** [comment]
OK, I have installed .NET 5 RC2, and it does try and use that.

Complete list of SDKs:
`PS C:\Projects\MOSoftwareEnterprises\dotnetnotts-web> dotnet --list-sdks
3.1.402 [C:\Program Files\dotnet\sdk]
3.1.403 [C:\Program Files\dotnet\sdk]
5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]   
PS C:\Projects\MOSoftwareEnterprises\dotnetnotts-web> `

With it set to `"rollForward": "latestMajor"`, we get it using .NET 5

`C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\MSBuild.dll -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\dotnet.dll -maxcpucount -restore -verbosity:m -verbosity:diag .\dotnetnotts.sln
Build started 15/10/2020 11:26:05.`


With the option set to `"rollForward": "latestFeature", it uses the latest version of 3.1 I have installed

`dotnet build -v diag` produces (snipped):
`C:\Program Files\dotnet\sdk\3.1.403\MSBuild.dll -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\3.1.403\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\3.1.403\dotnet.dll -maxcpucount -restore -verbosity:m -verbosity:diag .\dotnetnotts.sln
Build started 15/10/2020 11:22:46.`

**Pull request merged**
