### PR TITLE
Fixed error while redirecting to contributing.md

### PR DESCRIPTION
**Pull request by HarshalGoyal**
## Description of Change

Short description of changes.

## Evidence Of Change

Screen shots of the change working

## Linked Issue

Link to any issue related to this change i.e `#9`

### CODE REVIEW

**Review by pjgpetecodes — CHANGES_REQUESTED** [review]
Thanks! Can remove the whole stem of the URL you've entered and leave just the .`github/contribute.md` part...? That way it's all relative..

**Comment by HarshalGoyal** [comment]
@pjgpetecodes i did the change to make it relative sir.

**Review by pjgpetecodes — APPROVED** [review]
Fab work... Thanks!

**Comment by HarshalGoyal** [comment]
@pjgpetecodes i would like to work more on this repo and contribute to it as this is my first time contributing to open source.

**Comment by pjgpetecodes** [comment]
Fab stuff! If you hold off until October perhaps, then you can take part in Hacktoberfest too!

**Comment by HarshalGoyal** [comment]
@pjgpetecodes  Thanks for the advice , I just registered for the Hacktoberfest !

**Comment by pjgpetecodes** [comment]
Fab stuff!!

**Pull request merged**
