### PR TITLE
Feature: unit / component tests for frontend

### PR DESCRIPTION
**Pull request by LukeBillo**
## Description of Change

Using [bUnit](https://github.com/egil/bUnit) with xUnit (which bUnit depends on), I've added unit / component level tests for all of the existing components. 

## Evidence Of Change

You can see the tests running in my command line below:
dotnet test in Windows Terminal

## Linked Issue

This is linked to #30. 

I'm probably also going to do some acceptance level tests in a separate PR (so as not to make this PR large and unruly) since I was unable to test fully end-to-end here. There's also certain pieces of Blazor that are difficult to test with bUnit such as navigation, as `NavigationManager` can't be mocked easily.

### CODE REVIEW

**Review by pjgpetecodes — APPROVED** [review]
This life great @LukeBillo! Thanks!

**Review by pjgpetecodes — CHANGES_REQUESTED** [review]
@LukeBillo ... We've added tabbing to a few pages now which has broken a couple of tests...

image

Do you mind correcting those? Cheers....

**Comment by LukeBillo** [comment]
Sure thing @pjgpetecodes!

**Comment by LukeBillo** [comment]
@pjgpetecodes should be all fixed up 👍

**Comment by wordshaker** [comment]
Looks great @LukeBillo 
image

**Review by wordshaker — APPROVED** [review]

**Pull request merged**
