### PR TITLE
Fix sponsor logo display issue

### PR DESCRIPTION
**Pull request by chatRG**
## Description of Change

Changed sponsor to sponsor**s** since the former is a keyword for ad-blockers.

## Evidence Of Change

Screen shots of the change working
image

## Linked Issue

Link to any issue related to this change i.e #63

### CODE REVIEW

**Comment by chatRG** [comment]
@pjgpetecodes can you kindly review and merge if this looks good?

**Comment by pjgpetecodes** [comment]
I'll take a look and let you know... Thanks!

**Review by pjgpetecodes — APPROVED** [review]
Looks good...

**Comment by pjgpetecodes** [comment]
THanks @chatRG !

**Pull request merged**
