### PR TITLE
Adding code of conduct content

### PR DESCRIPTION
**Pull request by mosoftwareenterprises**
## Description of Change

Added the content of the code of conduct page from the original dotnetnotts website.
Adjusted the hyperlink colours to match. This will affect the whole site.
Added unit tests of the page too.

## Evidence Of Change

Here is a screenshot of the page from my machine:
image

## Linked Issue

This resolves issue #2

### CODE REVIEW

**Review by pjgpetecodes — CHANGES_REQUESTED** [review]
Hi @mosoftwareenterprises... Thanks..

Can you revert the change to the global.json file so it references version 3.1.401 of the Dot Net Core SDK?

Thanks!

**Comment by mosoftwareenterprises** [comment]
Sorry, I did not mean to commit that.
Sorting now.

**Comment by mosoftwareenterprises** [comment]
Just a thought - Could we remove the global.json all together, or perhaps configure it to just require Core 3.1? : https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x

**Comment by wordshaker** [comment]
> Just a thought - Could we remove the global.json all together, or perhaps configure it to just require Core 3.1? : https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x

I would be fine with that, but I'll wait for @pjgpetecodes  to comment

**Comment by pjgpetecodes** [comment]
The main issue is with the GitHub Actions Yaml... I'm not sure how to configure that to take the latest version rather than a specific version...

The section of the yaml affected is;

` - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.401'`

This page seems to infer that we can replace the minor version with an x... But, is this a special actions thingy for that repo or what?

https://github.com/actions/setup-dotnet

If that's the case, the global.json could be something like this I think;

`{
  "sdk": {
    "version": "3.1.200",
    "rollForward": "latestMajor"
  }
}`

I'll create another issue for this and feel free to put your hand up to have a crack at it...

**Review by pjgpetecodes — APPROVED** [review]
Looks good now... Thanks!

**Comment by pjgpetecodes** [comment]
The issue related to the global.json is here #61

**Pull request merged**
